---

- name: Basic playbook run locally 
  gather_facts: false 
  hosts: all 
  tasks: 
    - name: Doing a ping
      ping:

    - name: Show info
      debug:
        msg: "Machine name: {{ ansible_hostname }}"
